### ISSUE TITLE
Cannot read property 'beforeEach' of undefined

### ISSUE THREAD

**Issue by ohohco** [websanova/vue-jwt-auth#1]
I init my project with `vue-cli`,  and use `vue-jwt-auth` like this:
```
import Vue from 'vue'
import VueRouter from 'vue-router'
import App from './App'

Vue.use(require('vue-resource'))
Vue.use(VueRouter)

let router = new VueRouter()
router.map({
  '/admin': {
    auth: 'admin',
    component: require('./Admin')
  },
  '/login': {
    auth: false,
    component: require('./Login')
  }
})

Vue.use(require('vue-jwt-auth'))
router.start(App, 'app')

```  
It is complied well, but the browser console logged :  
`vue-jwt-auth.js?0fa3:329 Uncaught TypeError: Cannot read property 'beforeEach' of undefined...`

**Comment by lymanlai** [comment]
@ohohco ya, I got this problem too, I think there we do not have the Vue.router stuff

https://github.com/websanova/vue-jwt-auth/blob/master/vue-jwt-auth.js#L329

my solution is 
```
router.start(App, 'app', () => {
  Vue.router = router
  Vue.use(JwtAuth)
  console.log('=====done with load==== ' + new Date())
})
```

**Comment by websanova** [comment]
Not sure why, it's happening, but yes I think you can do:

```
Vue.router = new VueRouter();
```

Instead of 

```
let router = new VueRouter()
```

**Comment by websanova** [comment]
It's a bit tricky with the router since it's not always there on init.

I've created another option for instantiating the auth module. So it will check for `Vue.router` or you can optionally pass it in.

```
Vue.use(JwtAuth, {}, router);
```

**Comment by ohohco** [comment]
@websanova @lymanlai  's way is better. I follow your solution , and I update the `vue-jwt-auth` , now browser console logged:` vue-jwt-auth.js?5662:247Uncaught ReferenceError: Vue is not definedcreated ...`

**Comment by websanova** [comment]
If you are using the same example it's still not loading the `router`. Can I see the updates source of your code. Also can you copy and paste the line from the error for me, so I can see where it's happening exactly (it just shows 5662, not sure if that's from the compiled file).

**Comment by ohohco** [comment]
This is my code :  
```
import Vue from 'vue'
import VueRouter from 'vue-router'
import App from './App'

Vue.config.devtools = true

// config router
Vue.use(VueRouter)
const router = new VueRouter()
Vue.router = router
Vue.use(require('vue-jwt-auth'), {}, router)
router.map({
  '/admin': {
    auth: 'admin',
    component: require('./Admin')
  },
  '/login': {
    auth: false,
    component: require('./Login')
  }
})

router.start(App, 'app', () => {
  // Vue.use(require('vue-jwt-auth'))
  // Vue.router = router
  // Vue.use(require('vue-jwt-auth'), {}, router)
  console.log('=====done with load==== ' + new Date())
})

```

This is the errors:  
```
vue-jwt-auth.js?5662:247 Uncaught ReferenceError: Vue is not defined  
     created @ vue-jwt-auth.js?5662:247  
     Vue._callHook @ vue.common.js?b6d4:8199  
     Vue._init @ vue.common.js?b6d4:2453  
     Vue._init @ vue-router.js?2e68:1756  
     Vue @ vue.common.js?b6d4:9474
     install @ vue-jwt-auth.js?5662:420
    Vue.use @ vue.common.js?b6d4:9966
   (anonymous function) @ main.js?3479:11
   (anonymous function) @ app.js:649
   __webpack_require__ @ app.js:556
    fn @ app.js:87
   (anonymous function) @ app.js:587
   __webpack_require__ @ app.js:556
   (anonymous function) @ app.js:579
   (anonymous function) @ app.js:582
```

**Comment by websanova** [comment]
Ok, found the issue, thanks for reporting. Try the latest again v0.6.1.

Note that the pack is dependent on both `vue-router` and `vue-resource` modules.

```
import VueResource from 'vue-resource'
Vue.use(VueResource);
```
