### ISSUE TITLE
Can you Provide a demo for setting the  Plugin

### ISSUE THREAD

**Issue by FerchoCarcho** [websanova/vue-jwt-auth#12]
Hello! @websanova  Thank you for the Plugin.

I know it is asking too much, but your plugin is so good, it would be very helpfull If you could make a demo page for making it work !
I landed to your github account because Im having an Issue with my authenticated user trying to reach the /register page or /login page when he/she is already In. The strange situation is 
the this.$root.authenticated tell me false even it is set to True look at this image.
![untitled-1](https://cloud.githubusercontent.com/assets/11180135/17832972/9d8d18ac-66df-11e6-9859-4551d406e05c.jpg)

**Comment by websanova** [comment]
Where is that "authenticated" parameter coming from?

**Comment by FerchoCarcho** [comment]
Hello @websanova It is comming from  :   
Every route which will be transitioned to auth:true is verified with 
```
router.beforeEach(function (transition) {

    var token = localStorage.getItem('jwt-token')
    if (transition.to.auth) {

        if (!token || token === null) {
            console.log('redirecting to Login');
            transition.redirect('/login')
        }
    }
    transition.next()
});
```
When the user reaches login, sets its credentials, then 
```
 ready: function () {
 var token = localStorage.getItem('jwt-token')
        if (token !== null && token !== 'undefined') {
            var that = this

            client({ path: 'try/users/me' }).then(
                function (response) {
                    that.setLogin(response.entity);
                    that.$broadcast('data-loaded')
                },
         } )
        },
```
a  this.authenticated Variable is set at the root component to let know the user is already login saying that logged in wants to go to /register or  /login this variable will be checked to redirect to other place.
```
methods: {

        setLogin: function (user) {
            this.user = user;
            this.authenticated = true;
            this.token = localStorage.getItem('jwt-token')
        },
```

**Comment by FerchoCarcho** [comment]
at the register.vue child component I have the following to verify the this.$root.authenticated variable
but it is giving me False even when at the vue devtools or ``` $data |json  ```shows it is set to true.
```
 module.exports = {
        route: {
                activate: function (transition) {
                    console.log(this.$root.authenticated,'$root.authenticated');
                    console.log(this.$root.$data.authenticated,'$root.$data.authenticated')
                   
```

**Comment by websanova** [comment]
That variable is stored in the user object. You can just use
`$auth.check()` in your code. Bad idea to use variables directly, could
easily change in future versions.

**Comment by FerchoCarcho** [comment]
I'm willing to refactor my code with your plugin, because as I saw yours is the logic I would like to have on my website. 
Because of that I was asking for a Demo. It would be very useful to other users too.
